### ISSUE TITLE
`url()` with params and `param { }` works not obvious together

### ISSUE THREAD

**Issue by rybalkinsd** [rybalkinsd/kohttp#94]
At the moment we ignore `url( )` parameters.

It would be better if we will add them as a primary source of params.

checklist:
- [x]  "path/?a=b"
- [x] "path?a=b"
- [x] "path/?a=b&c=&d=123"
- [x] "path?a=b#tag"
- [x] "path?a=xxx&a=&a=yyy

**Comment by dtropanets** [comment]
Hey. I'd say this is an issue, because it is not obvious that `url` extension ignores parameters. In our case, we passed the URL provided from the API and lost parameters, resulting in failed request.

**Comment by rybalkinsd** [comment]
Hi @dtropanets , could you please submit a code sample? It would be very helpful for us to see the concrete problem. We're checking our options to clarify `url { }` logic

**Comment by dtropanets** [comment]
What I meant is if you receive a URL from some API ("https://api.github.com/users/whatever?client_id=xxxx") and pass it to the `url()`, `client_id=xxxx` parameter will be ignored, because `url()` doesn't add parameters to the builder. This is not obvious, since user is expecting that the whole url will be used for request. I think, using both `url()` and `param { }` as a source of parameters is perfectly fine. As example, user can have some url (again, "https://api.github.com/users/whatever?client_id=xxxx") as a base for requests and then add additional params using `pasram { }`.

I can make a PR with this change, it should be quite straightforward.

**Comment by rybalkinsd** [comment]
I see, make sense. Added some notes and a checklist to the issue description.
PRs are always welcome!

**Comment by rybalkinsd** [comment]
https://github.com/rybalkinsd/kohttp/tree/fix/94-url-params here are several fixes over the whole codebase according to this fix. The plan is to merge them together with @dtropanets 's PR

**Comment by rybalkinsd** [comment]
0.10.0
